import { Link } from 'react-router-dom'

const features = [
  {
    icon: '🔬',
    title: 'Instant OCR Extraction',
    desc: 'Upload a PDF, JPG or PNG scan. Our pipeline reads your lab report automatically — no typing needed.',
  },
  {
    icon: '📊',
    title: 'Plain-English Results',
    desc: 'Every biomarker is flagged as Normal, Low, High, or Critical and explained in language anyone can understand.',
  },
  {
    icon: '🤖',
    title: 'AI-Powered Insights',
    desc: 'Context-aware explanations generated by an LLM, enriched with your medical history and past reports.',
  },
  {
    icon: '🔒',
    title: 'Private & Secure',
    desc: 'Reports stored in a private encrypted bucket. Row-Level Security ensures only you can see your data.',
  },
]

const stats = [
  { value: '3+', label: 'Test Panels Supported' },
  { value: '< 30s', label: 'Average Processing Time' },
  { value: '100%', label: 'Private by Design' },
]

export default function LandingPage() {
  return (
    <div className="landing-root">
      {/* ── NAV ── */}
      <header className="landing-nav">
        <span className="landing-brand">Medi<span>Clear</span></span>
        <div className="landing-nav-actions">
          <Link to="/login" className="btn btn-ghost" id="nav-login-btn">Sign in</Link>
          <Link to="/signup" className="btn btn-primary" id="nav-signup-btn">Get started free</Link>
        </div>
      </header>

      {/* ── HERO ── */}
      <section className="landing-hero">
        <div className="landing-hero-glow" aria-hidden="true" />
        <div className="landing-hero-content">
          <div className="landing-pill">🧬 Medical Report Translator</div>
          <h1 className="landing-headline">
            Understand your lab<br />
            results in <span className="landing-highlight">plain English</span>
          </h1>
          <p className="landing-subheadline">
            Upload any blood test PDF or scan. MediClear extracts every biomarker,
            flags what's outside range, and explains what it means — in seconds.
          </p>
          <div className="landing-cta-group">
            <Link to="/signup" className="btn landing-btn-hero" id="hero-signup-btn">
              Get started free →
            </Link>
            <Link to="/login" className="btn btn-ghost landing-btn-login" id="hero-login-btn">
              Sign in to my account
            </Link>
          </div>
          <p className="landing-disclaimer">
            ⚕️ MediClear is an informational tool. It does not diagnose, prescribe, or replace a doctor.
          </p>
        </div>
      </section>

      {/* ── STATS ── */}
      <section className="landing-stats-row">
        {stats.map((s) => (
          <div key={s.label} className="landing-stat">
            <div className="landing-stat-value">{s.value}</div>
            <div className="landing-stat-label">{s.label}</div>
          </div>
        ))}
      </section>

      {/* ── HOW IT WORKS ── */}
      <section className="landing-section">
        <h2 className="landing-section-title">How it works</h2>
        <div className="landing-steps">
          {[
            { n: '01', title: 'Upload your report', desc: 'PDF, JPG, JPEG or PNG — scanned or digital.' },
            { n: '02', title: 'We process it', desc: 'OCR extracts text; the parser identifies every test and value.' },
            { n: '03', title: 'Get your results', desc: 'See status badges, reference ranges, and AI explanations instantly.' },
          ].map((step) => (
            <div key={step.n} className="landing-step">
              <div className="landing-step-num">{step.n}</div>
              <div>
                <div className="landing-step-title">{step.title}</div>
                <div className="landing-step-desc">{step.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section className="landing-section">
        <h2 className="landing-section-title">Everything you need</h2>
        <div className="landing-features">
          {features.map((f) => (
            <div key={f.title} className="landing-feature-card">
              <div className="landing-feature-icon">{f.icon}</div>
              <div className="landing-feature-title">{f.title}</div>
              <div className="landing-feature-desc">{f.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── CTA BANNER ── */}
      <section className="landing-cta-banner">
        <div className="landing-cta-banner-glow" aria-hidden="true" />
        <h2 className="landing-cta-banner-title">Ready to read your report?</h2>
        <p className="landing-cta-banner-sub">Create a free account and upload your first report in under a minute.</p>
        <Link to="/signup" className="btn landing-btn-hero" id="bottom-signup-btn">
          Create free account →
        </Link>
      </section>

      {/* ── FOOTER ── */}
      <footer className="landing-footer">
        <span className="landing-brand" style={{ fontSize: '1rem' }}>Medi<span>Clear</span></span>
        <span className="landing-footer-copy">© {new Date().getFullYear()} MediClear — For informational use only.</span>
      </footer>
    </div>
  )
}
